### ISSUE TITLE
Problema arrotondamenti e decimali nell’editor del bene

### ISSUE THREAD

**Issue by armandomusto** [EmmeEsse/ESSE#1]
Punto 1.
Bisogna controllare un po’ le caselle di input dei valori degli immobili. Se inserisci un valore decimale nella casella rendita, sei obbligato a usare il punto ma sarebbe più corretto la virgola; anche perché il risultato poi viene visualizzato con la virgola:
Quando inserisci una cifra piccola, sempre nella casella rendita, ad es. 0,0015 il valore viene arrotondato all’euro. E questo è corretto ma ci dobbiamo ricordare che questo funzionamento automatico deve essere opzionabile. Alla fine, però, con questi valori piccolissimi mi ha sballato la somma nella finestra della ripartizione dei valori ai successori:

![image](https://cloud.githubusercontent.com/assets/4960206/4952664/5f3b946c-6677-11e4-95bb-3e8a13d51b56.png)

Lo stesso problema avviene anche per le azioni:

![image](https://cloud.githubusercontent.com/assets/4960206/4952670/7ad2d082-6677-11e4-960d-b0da9b1a68fa.png)

Punto 2.
poi ho cercato di correggere a mano il valore, nella casella del totale compariva il numero intero ma comunque non mi faceva andare avanti.

![image](https://cloud.githubusercontent.com/assets/4960206/4952681/95e77710-6677-11e4-9975-df6d42e6504d.png)

**Comment by armandomusto** [comment]
Punto 1.
L’errore generato dai numeri piccoli è dovuto al fatto che la colonna del valore è arrotondata a 2 cifre decimali. Attualmente il problema è stato risolto portando a 5 cifre decimali la gestione dei valori. Sarà creata un’opzione per gestire il numero di cifre decimali. Tutti i valori dovranno avere lo stesso numero di cifre decimali sia per l’inserimento che per la stampa. Questa funzionalità dovrà essere testata di nuovo dopo la gestione delle opzioni vedi bug #7 .

Punto 2.
Perché è attiva l’opzione arrotonda all’euro

**Comment by armandomusto** [comment]
Questo dovrebbe essere già stato sistemato dall'ultimo aggiornamento. Controlla.

**Comment by skate68** [comment]
Ok
