### ISSUE TITLE
Completare sezione del dichiarante

### ISSUE THREAD

**Issue by armandomusto** [EmmeEsse/ESSE#12]
Completare il dichiarante sia nelle Opzioni dell'applicazione sia nelle Opzioni del file

**Comment by armandomusto** [comment]
La gestione del dichiarante è completa al 90%. Mancano ancora da completare:
- [x] Campi obbligatori
- [x] Fix su selezione "Inserisci il dichiarante di default", la scritta scompare subito dopo aver selezionato (il problema deriva dal fatto che viene resettato il valore nella proprietà Cognome)

**Comment by skate68** [comment]
![image](https://cloud.githubusercontent.com/assets/9605890/5730393/fa666598-9b79-11e4-95b1-e0f768e126c1.png)

**Comment by armandomusto** [comment]
Vedi #72
