### ISSUE TITLE
Modifica editor Bene : Azioni

### ISSUE THREAD

**Issue by armandomusto** [EmmeEsse/ESSE#13]
Trasformare il campo “Descrizione delle agevolazioni” in un campo stile Memo come quello della Descrizione

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
A me non risulta questa modifica:
![image](https://cloud.githubusercontent.com/assets/9605890/5577137/d650b8ea-900a-11e4-8166-a55fb268980c.png)

**Comment by armandomusto** [comment]
Scarica l'aggiornamento, l'ho fatto ieri sera tardi

**Comment by skate68** [comment]
Ok
