### ISSUE TITLE
Gestione opzioni e impostazioni file

### ISSUE THREAD

**Issue by armandomusto** [EmmeEsse/ESSE#14]
Quando si crea un nuovo file le opzioni sono recuperate dalle opzioni di default dell’applicazione e salvate all’interno del file. L’applicazione userà sempre e solo le impostazioni salvate all’interno del file. Nel panello di gestione delle impostazioni/opzioni sarà disponibile un bottone per salvare le impostazioni correnti come default. La vista ToolView dovrà gestire sia le opzioni di default che quelle del file. Quando si lancia l’applicazione e l’utente apre la vista degli strumenti senza aver caricato il file allora devono essere caricate le impostazioni di default, se invece si accede a questa pagina quando è aperto un file allora deve caricare le impostazioni dal file e rendere visibile il bottone “Salva come default”.
- [x] Arrotonda all’euro
- [x] Stampa simbolo valuta (euro) nei report
- [x] Numero di cifre decimali da usare nei calcoli del bene
- [x] Dati del dichiarante. In questa sezione viene salvato il dichiarante di default dell’applicazione che può essere usato nel caso in cui il dichiarante non sia stato selezionato tra i successori
- [x] Radio Box per selezione tipologia di albero da stampare: testuale o grafico

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
Dove compare il bottone salva come default?
![image](https://cloud.githubusercontent.com/assets/9605890/5730375/dcd275a8-9b79-11e4-925a-4f616fbad632.png)
