### ISSUE TITLE
Errore generazione albero grafico con collaterali

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#18]
La routin di generazione dell'albero grafico fa errore quando ricostruisco una gerarchia sul ramo collaterale. L'errore è sistematico perché me lo fa con un file vecchio e anche con uno nuovo: Test_27_Albero_grafico_Coniuge_Collaterali.msu; ma puoi provare anche con uno dei precedenti file Test_23..... che trovi tutti in dropbox.

![image](https://cloud.githubusercontent.com/assets/9605890/4955281/2a0694aa-6694-11e4-971e-cb2fb296c0c6.png)

**Comment by armandomusto** [comment]
Prima di inserire un nuovo issue verifica che non ci sia già #11

**Comment by skate68** [comment]
Il problema persiste anche con un file nuovi. faccio l'attach dell'interfaccia perchè così ti rendi conto se stiamo usando la stessa versione.
![image](https://cloud.githubusercontent.com/assets/9605890/4972802/7898fb98-68b1-11e4-9a25-737723c958c5.png)

**Comment by armandomusto** [comment]
Ho dimenticato di aggiornare la cartella con la nuova release.Riprova adesso

**Comment by skate68** [comment]
la generazione dell'albero automatico è una bomba! Bisogna solo sistemare questa piccola cosa
![image](https://cloud.githubusercontent.com/assets/9605890/5035508/12f2f1bc-6b78-11e4-881c-4d19730aba2a.png)

**Comment by armandomusto** [comment]
Problema risolto. Aggiornamento su DropBox.

**Comment by skate68** [comment]
Controllo eseguito. Ok!
