### ISSUE TITLE
Input successori - inibire la possibilità di inserire due coniugi

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#20]
Guarda qui:
![image](https://cloud.githubusercontent.com/assets/9605890/4955363/bb7796aa-6694-11e4-8d29-0156db491398.png)

**Comment by armandomusto** [comment]
Problema risolto. Aggiornamento su Dropbox.

**Comment by skate68** [comment]
Controllo eseguito. A posto!
