### ISSUE TITLE
Modifica layout header griglia

### ISSUE THREAD

**Issue by armandomusto** [EmmeEsse/ESSE#22]
- [ ] Sostituire il colore rosso con arancio. 
- [ ] Sostituire le icone 
- [x] Sistemare le caption negli headers sono troncate.

![image](https://cloud.githubusercontent.com/assets/4960206/4955989/1230c1fc-6699-11e4-99dc-ea906ea6f1eb.png)

**Comment by armandomusto** [comment]
TI piace se anzichè rosso usiamo l'arancione per le testate?

**Comment by skate68** [comment]
Sì. Però poi non è che stanca? E se proviamo con una. Si può fare?
Il 07/nov/2014 17:16 "armandomusto" notifications@github.com ha scritto:

**Comment by armandomusto** [comment]
E' per uniformare i colori senza usarne troppi. SI può impostare su una sola griglia per test.

**Comment by skate68** [comment]
Ma il grigio rimane?
Il 07/nov/2014 17:23 "armandomusto" notifications@github.com ha scritto:

**Comment by armandomusto** [comment]
Si, è solo l'header che cambia. In questo modo sembra tutto più uniforme

![image](https://cloud.githubusercontent.com/assets/4960206/4957438/6ccde6a2-66a4-11e4-8095-69e4e96e507a.png)

**Comment by skate68** [comment]
Ok! Mi piace pure a me
Il 07/nov/2014 18:13 "armandomusto" notifications@github.com ha scritto:

**Comment by skate68** [comment]
Ok! Questa  per me è sistemata
