### ISSUE TITLE
Ascendenti premorti o rinunciatari nell'albero genealogico

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#25]
Gli ascendenti premorti o rinunciatari non vanno riportati di default nell'albero genealogico:
![image](https://cloud.githubusercontent.com/assets/9605890/5164659/a2378436-73da-11e4-8adb-39ca39549f67.png)

![image](https://cloud.githubusercontent.com/assets/9605890/5164649/8472dfe0-73da-11e4-8669-016239fbfa60.png)

**Comment by armandomusto** [comment]
Gestione Check "Stampa quadro A" e "Mostra nell'albero genealogico" per gli ascendenti deceduti o rinunciatari gestito.
Immagine tagliata risolta.

**Comment by armandomusto** [comment]
Se sicuro che l'ascendente premorto vada rimosso dall'albero grafico?

**Comment by skate68** [comment]
Certo. Nei rami discendente e quello generato dai fratelli c'è il diritto
di rappresentazione così bisogna ricostruire i passaggi; mentre nel ramo
ascendente questo diritto non esiste. Procedi tranquillamente
Il 28/nov/2014 21:54 "armandomusto" notifications@github.com ha scritto:

**Comment by armandomusto** [comment]
Problema risolto. Aggiornamento su Dropbox

**Comment by skate68** [comment]
Nell'assegnazione del valore di un bene  successori ci sono delle incongruenze secondo me derivanti dalla gestione degli elementi da visualizzare nell'albero genealogico:
![image](https://cloud.githubusercontent.com/assets/9605890/5243762/21c49474-7948-11e4-827a-568449ea2b96.png)

Dovresti gestire le tre categorie (successori, ascendenti e collaterali) con i controlli indicati sotto già dal momento dell'inserimento:
![image](https://cloud.githubusercontent.com/assets/9605890/5243782/5ba7730a-7948-11e4-8f2d-4ebe35c17c39.png)

Perché adesso fa questi casini che vedi sotto:
![image](https://cloud.githubusercontent.com/assets/9605890/5243793/7bf746c6-7948-11e4-8590-628e1343073f.png)

Arma' se puoi fai partire il sistema di default con due cifre decimali perché adesso è ingestibile:
![image](https://cloud.githubusercontent.com/assets/9605890/5243809/c5834358-7948-11e4-8481-da6c9fe2d54b.png)

**Comment by armandomusto** [comment]
Da testare. Su dropbox.
