### ISSUE TITLE
Errore stampa albero genealogico testuale

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#26]
Ecco cosa stampa nel documento nella parte relativa alla generazione dell'albero genealogico testuale:
![image](https://cloud.githubusercontent.com/assets/9605890/5164701/1b56f108-73db-11e4-975a-880d28cf27d3.png)

**Comment by armandomusto** [comment]
Risolto. Puoi scaricare l'aggiornamento.

**Comment by skate68** [comment]
Buongiorno Arma'. Lo trovo già su dropbox?
Il 26/nov/2014 08:02 "armandomusto" notifications@github.com ha scritto:

**Comment by armandomusto** [comment]
Si

**Comment by skate68** [comment]
C'è ancora qualcosa che non va:
![image](https://cloud.githubusercontent.com/assets/9605890/5197762/9c97498a-7547-11e4-86a1-106d11df7427.png)

La stessa diagnostica mi compare anche se provo a creare un nuovo file, proprio quando clicco su nuova.

Poi un file che si è aperto (il Test_26...) anche se era selezionato Testuale continua a mandare in stampa l'albero grafico nel modo che vedi di seguito:
![image](https://cloud.githubusercontent.com/assets/9605890/5197790/e8078e16-7547-11e4-9d8c-333c06349177.png)

**Comment by armandomusto** [comment]
Problema risolto. Aggiornamento su DropBox.

**Comment by skate68** [comment]
Adesso non compare più l'immagine nera ma ci sono ancora dei problemi:
![image](https://cloud.githubusercontent.com/assets/9605890/5243696/27344798-7947-11e4-8d5f-b4693e9aa07d.png)

Riferisciti ai file aggiunti in dropbox dove troverai diversi successori ma qui ne stampa solo uno:
![image](https://cloud.githubusercontent.com/assets/9605890/5243713/52507672-7947-11e4-9b04-2a2946217a8f.png)

Inoltre dovresti uniformare i caratteri perché adesso nella finestra di anteprima sono di un tipo nella stampa di un altro.

**Comment by armandomusto** [comment]
Risolto. Nuova versione disponibile su DropBox

**Comment by skate68** [comment]
Ci siamo quasi:
in figura sotto ti mostro il risultato dell'albero testuale in anteprima:
![image](https://cloud.githubusercontent.com/assets/9605890/5295270/d00ef09e-7b94-11e4-896f-e380427a8650.png)

Invece questo è il risultato di stampa:
![image](https://cloud.githubusercontent.com/assets/9605890/5295274/e83f9998-7b94-11e4-84e6-2610ef2cbdf1.png)

Poi, ti ripeto, cerca uniformare il font utilizzato nel resto del documento, così si trova già tutto predisposto per quando seguiremo l'opzione scelta dall'utente. 
Nell'albero grafico, se puoi, dovresti provare a stampare tutti i dati degli elementi in ciascun relativo box. Anche qui ci troveremo il lavoro quasi completato e potremmo chiudere il discorso a breve.
Buon lavoro!

**Comment by skate68** [comment]
![image](https://cloud.githubusercontent.com/assets/9605890/5295331/e0970e28-7b95-11e4-8005-19363ac3063e.png)

**Comment by armandomusto** [comment]
Da testare. Su dropbox.

**Comment by skate68** [comment]
Arma' mi dispiace ma penso che ci dobbiamo vedere u attimo da vicino e ragionare un po' per bene su questa funzionalità del software. questo è quello che ottengo sul mio computer in più test:
![image](https://cloud.githubusercontent.com/assets/9605890/5323595/0549bb84-7cd2-11e4-8240-283162315582.png)

![image](https://cloud.githubusercontent.com/assets/9605890/5323607/0ec28786-7cd2-11e4-8537-dc56e38d3310.png)

![image](https://cloud.githubusercontent.com/assets/9605890/5323611/1b646004-7cd2-11e4-837e-9f42e2ffc97e.png)

**Comment by armandomusto** [comment]
Per adesso è ancora un'immagine, ma per lo meno è indipendente dalla risoluzione dello schermo (almeno spero). 
Aggiornamenti in dropbox. Scarica anche i modelli

**Comment by skate68** [comment]
Armando ci siamo quasi. Adesso mi pare che comincia a funzionare dobbiamo solo limare un po' di cose:
![image](https://cloud.githubusercontent.com/assets/9605890/5347221/07639320-7f27-11e4-9afa-446e3815a146.png)

Ti aggiungo un esempio di come dovrebbe essere il risultato finale:
![image](https://cloud.githubusercontent.com/assets/9605890/5347236/1ecd2936-7f27-11e4-85f4-5f7884c0586c.png)

Invece guarda il risultato che mi aveva dato con un file vecchio:
![image](https://cloud.githubusercontent.com/assets/9605890/5347347/cda78122-7f27-11e4-8b39-da88075e5ab0.png)
Il file era Test_28... quindi con diversi successori

**Comment by armandomusto** [comment]
Per adesso credo vada bene. A parte qualche altra piccola miglioria. Aggiornato DropBox
