### ISSUE TITLE
Albero grafico e testuale

### ISSUE THREAD

**Issue by armandomusto** [EmmeEsse/ESSE#27]
A) Albero grafico
- [x] Bug: Attualmente le modifiche apportate all'albero si perdono perché ogni volta che l'albero viene visualizzato viene rigenerato. Per risolvere questo problema si dovrebbe serializzare il contenuto della proprietà StreamData. Inoltre tale salvataggio dovrebbe essere realizzato ogni volta che si modifica intenzionalmente il grafico.
- [ ] CR: Quando non ci sono discendenti i collaterali, se presenti potrebbero essere visualizzati al posto dei discendenti ottimizzando lo spazio.

B) Albero Testuale
- [x] CR: E' possibile salvare l'albero testuale in un file rtf e visualizzarlo all'interno del documento. Attualmente ci sono problemi di formattazione con questa soluzione, ma è migliore rispetto ad utilizzare un'immagine come è adesso. Si potrebbe pensare di sostituire il FlowDocumentScrollViewer con il RichTextBox e poi salavre l'albero in formato docx anzichè rtf.

**Comment by skate68** [comment]
C) C'è da sistemare lo stile del testo dell'albero testuale che solo in questa parte del comuento continua a non seguire l'impostazione generale (courier new corpo 9) che funziona dappertutto
![image](https://cloud.githubusercontent.com/assets/9605890/5541020/e4b7c834-8ad2-11e4-950d-220344ba2bfb.png)

**Comment by armandomusto** [comment]
Risolto il punto C), aggiornamento su Git HUB. Utilizzato Courier New 8 per contenere le dimensioni.

**Comment by skate68** [comment]
Nel file: Test31.... allegato ho inserito un fratello in una successione con coniuge e figli. Quindi (correttamente) non gli è stata assegnata alcuna quota; ma i controlli di visualizzazione nella dialog dei successori non sono stati settati correttamente come dovevano: Stampa nel quadro A = False, Stampa nell'albero genealogico = False (anche se avesse avuto figli questi non avrebbero avuto diritto all'eredità. Però poteva capitare, in una eventuale successione testamentaria, che avrei voluto visualizzarlo nell'albero e nel quadro. Il programma adesso consente di gestire la stampa solo nel quadro A ma non nell'albero perché a prescindere da come è settato questi non viene visualizzato nell'albero genealogico. La procedura automatica di assegnazione delle quote deve provvedere a settare i due controlli per ogni successore e poi deve seguire le eventuali indicazione impartite dall'utente. In questo caso i due controlli devono essere settati a false e poi decidere di stampare tutti gli elementi seguendo esclusivamente l'impostazione dei due controlli.

**Comment by armandomusto** [comment]
Se i due flag devono essere pilotati dalla procedura automatica di assegnazione delle quote allora non è possibile usare i settaggi impostati dall'utente. Attualmente i flag sono completamente impostati dall'utente, quando inserisci il Fratello i due flag sono a True (infatti il fratello è visibile sia nell'albero che le quadro A). L'unica cosa che si può fare è preimpostare i due flag nel caso di creazione di un nuovo successore verificando se potenzialmente ha le caratteristiche per essere visualizzato.

**Comment by skate68** [comment]
Sì così andrebbe bene. Solo in una prova che ho fatto ieri sera il frtello
non veniva stampato nell'albero grafico comunque settavo il relativo
controllo.
Il 27/dic/2014 11:06 "armandomusto" notifications@github.com ha scritto:

**Comment by armandomusto** [comment]
Ma questo controllo funziona solo parzialmente, perchè dipende dall'ordine con cui si inseriscono i successori. Se inserisci i collaterali prima dei discendenti non funzionerebbe...

**Comment by skate68** [comment]
Arma va bene come dici tu basta che se l'utente vuole visualizzarlo o no
nei due luoghi può farlo. E siamo a posto
Il 27/dic/2014 15:52 "armandomusto" notifications@github.com ha scritto:

**Comment by armandomusto** [comment]
Un controllo formale è stato aggiunto, ma dipende sempre dallo stato corrente dell'albero.

**Comment by skate68** [comment]
Se decidi di non stampare un erede nell'albero genealogico lo stesso non viene tenuto in considerazione nell'assegnazione dei valori dei beni agli eredi. Proprio in questa parte del programma c'è ancora qualche errore se scegli di visualizzare le quote in millesimi:
![image](https://cloud.githubusercontent.com/assets/9605890/5576929/b26989d8-9006-11e4-8716-fadf08b28f3d.png)

**Comment by armandomusto** [comment]
Mandami il file che genera questo errore. Io non riesco a replicarlo.

**Comment by skate68** [comment]
File Test31_successione_multidata aggiunto in dropbox

Il giorno 30 dicembre 2014 10:27, armandomusto notifications@github.com
ha scritto:

**Comment by armandomusto** [comment]
Ogni bene salva un elenco dei successori aventi diritto alla quota di quel bene. Per un motivo che adesso non so e non riesco a replicare è stato salvato un elemento (il fratello) che non aveva diritto (indipendentemente dai flag selezionati dall'utente). Per risolvere questo problema basta aprire a salvare un elemento dell'albero e gli elenchi dei successori dei beni si rigenereranno. E' necessario però avere la nuova versione del programma.
