### ISSUE TITLE
Finestra grafica word processor integrato

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#29]
Quando si lancia la stampa di un qualsiasi documento, bisognerebbe far partire l'applicazione con maximize windows e il documento visualizzato all'interno deve occupare quasi tutta la larghezza dello spazio di visualizzazione:
Adesso è così:
![image](https://cloud.githubusercontent.com/assets/9605890/5541125/29abedb6-8ad4-11e4-8052-390dbcce98c6.png)
e dovrebbe diventare così:
![image](https://cloud.githubusercontent.com/assets/9605890/5541129/382bb6c8-8ad4-11e4-87f6-42a27872daa5.png)

**Comment by armandomusto** [comment]
Risolto, aggiornamento su Git hub

**Comment by skate68** [comment]
Controllato. Funziona Ok. La chiudo
