### ISSUE TITLE
Gestione beni immobili

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#30]
Mancano le righe per l'immissione delle osservazioni (commenti e note che l'utente desidera eventualmente aggiungere per descrivere il bene inserito in dichiarazione):

![image](https://cloud.githubusercontent.com/assets/9605890/5541191/e1434be0-8ad4-11e4-8e8c-e6f2d68d7094.png)

**Comment by skate68** [comment]
Il campo Ettari deve avere la seguente formattazione 00.00.00

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
ok! A posto
