### ISSUE TITLE
Stampa Modello 4 (b)

### ISSUE THREAD

**Issue by armandomusto** [EmmeEsse/ESSE#31]
- [x] 1) Il Quadro B:1 e il B:4 non vengono generati se non presenti beni di questi due tipi.
- [x] 2) Numerazione dei progressivi: quando si raggiungono numeri a due o più cifre scalare le posizioni nelle tre caselle:
  ![image](https://cloud.githubusercontent.com/assets/9605890/5558948/9031eb18-8d3a-11e4-910b-2e7a8a58dc20.png)
- [x] 3) Nel file Test_31... (allegato) ho inserito #10 immobili ma ne vengono stampati solo #8. Praticamente solo le prime due pagine su tre. La terza avrebbe dovuto contenere i beni 9 e 10.
- [x] 4) 
  ![image](https://cloud.githubusercontent.com/assets/9605890/5558847/ec0cdbe0-8d36-11e4-9b38-3885309a0a47.png)

**Comment by armandomusto** [comment]
Risolti punti 1,2,3,4. Nuovo aggiornamento su Git Hub.

**Comment by skate68** [comment]
Ok
