### ISSUE TITLE
Gestione beni asse ereditario

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#33]
Errore duplicazione beni dopo salvataggio

**Comment by skate68** [comment]
L'errore di cui parlavo nel commento precedente è il seguente:
![image](https://cloud.githubusercontent.com/assets/9605890/5562016/d98b130a-8dff-11e4-9979-0f133bba9120.png)

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
Ok! A posto, manca però ancora la possibilità di ordinamento dei beni
