### ISSUE TITLE
Stampa modello 4 (c)

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#34]
Errore generato in fase di stampa quando si aggiungono più di quattro elementi del tipo: D (passività):
![image](https://cloud.githubusercontent.com/assets/9605890/5562027/6d5f6b58-8e00-11e4-840f-b31eadba3c4d.png)

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
Ok! A posto
