### ISSUE TITLE
Stampa modello 4 (d)

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#35]
Errore generato nella fase di stampa del quadro B:3 (aziende) del modello 4:
![image](https://cloud.githubusercontent.com/assets/9605890/5562030/c9a376ca-8e00-11e4-8275-b6266fbe2caf.png)
![image](https://cloud.githubusercontent.com/assets/9605890/5562032/d60196c2-8e00-11e4-9641-7af5475cc843.png)

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
ok! A posto
