### ISSUE TITLE
Stampa modello 4 (f)

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#37]
Errore generato nella fase di stampa del quadro B:5 (beni trasferiti) del modello 4. La distribuzione degli elementi sulle pagine aggiuntive presenta qualche incongruità (vedi immagine)
![image](https://cloud.githubusercontent.com/assets/9605890/5562048/6bb79b76-8e01-11e4-8bf2-8d6f6f026ca4.png)

Inoltre la numerazione progressiva deve essere cambiata come quella proposta sotto:
![image](https://cloud.githubusercontent.com/assets/9605890/5562051/a0b3fad6-8e01-11e4-9128-353b251faa26.png)

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
Ok! A posto
