### ISSUE TITLE
Stampa modello 4 (g)

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#38]
Errore generato nella fase di stampa del quadro C (donazioni) del modello 4. La numerazione progressiva sulla pagina aggiuntiva non è corretta:

![image](https://cloud.githubusercontent.com/assets/9605890/5562055/d9a78812-8e01-11e4-8765-292e97f22476.png)

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
Ok! A posto
