### ISSUE TITLE
Ordinamento elenco beni asse ereditario

### ISSUE THREAD

**Issue by armandomusto** [EmmeEsse/ESSE#39]
- [x] Prevedere due frecce (Su/Giù), drag&drop se possibile, per cambiare l'ordinamento dei beniu nella griglia all'interno del proprio gruppo
- [x] Quando si elimina un bene bisogna ricalcolare il progressivo del bene

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
Ok a posto
