### ISSUE TITLE
Gestione CAP nell'indirizzo

### ISSUE THREAD

**Issue by armandomusto** [EmmeEsse/ESSE#41]
creare una nuova tabella dove sono salvati tutti i cap e collegarla alla tabella dei comuni. Quando si seleziona un comune viene tirato su anche il CAP (o i cap) collegati.
Nell'interfaccia, dove compare l'indirizzo con il comune sostituire il CAP con una combo box che deve essere riempita con i CAP del comune selezionato.

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
ok verificato
