### ISSUE TITLE
Albero testuale. Salvataggio file

### ISSUE THREAD

**Issue by armandomusto** [EmmeEsse/ESSE#46]
Il file che contiene l'albero, generato dinamicamente dall'applicazione deve essere salvato all'interno della successione per poter essere trasferito insieme ad essa.
Inoltre si deve evitare che eventuali modifiche a file, fatte con il word processor, siano sovrascritte dalla generazione automatica a meno che non ci sia una modifica della struttura dell'albero.

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
Ok
