### ISSUE TITLE
Gestione asse ereditario - Beni immobili

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#52]
Arma' penso che sarebbe meglio disporre le caselle della dialog relativa i beni immobili in questo modo:
![image](https://cloud.githubusercontent.com/assets/9605890/5577045/1aa268e2-9009-11e4-93b5-3d4ccc8cf12e.png)
![image](https://cloud.githubusercontent.com/assets/9605890/5577050/296c807e-9009-11e4-9afc-84f26941181e.png)

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
Controllato. A posto!
