### ISSUE TITLE
Stampa Modello 4 - Aziende B3

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#53]
Gestire meglio la lunghezza delle righe di descrizione dei beni:
![image](https://cloud.githubusercontent.com/assets/9605890/5577065/8f446934-9009-11e4-9aa3-2ff6301e06ed.png)

**Comment by armandomusto** [comment]
E che so i numeri rò banco lotto....
Per ora la lunghezza delle stringhe è uguale per tutte le righe della stessa pagina
