### ISSUE TITLE
Input dati generali

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#55]
C'è qualche problema di interfaccia con la griglia delle successioni precedenti:
![image](https://cloud.githubusercontent.com/assets/9605890/5577097/3df6e47a-900a-11e4-98dc-90aa0344a72e.png)

**Comment by armandomusto** [comment]
La griglia è stata sistemata. Per quanto riguarda la visualizzazione, per adesso il layout è organizzato per 1280x900.

**Comment by skate68** [comment]
Controllato. A posto!
