### ISSUE TITLE
Eliminazione Menù 

### ISSUE THREAD

**Issue by armandomusto** [EmmeEsse/ESSE#59]
Questo menù deve essere eliminato quando si apre il wizard della successione
![image](https://cloud.githubusercontent.com/assets/4960206/5601869/24e8f7dc-9322-11e4-9110-6f3f03cb08b8.png)

Ad eccezione del comando Strumenti. Quando si clicca su Strumneti anziche navigare cambiando vita si apre una finestra

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
Ok a posto!
