### ISSUE TITLE
Salvataggio file aperto quando si clicca sul bottone Chiudi

### ISSUE THREAD

**Issue by armandomusto** [EmmeEsse/ESSE#6]
Quando si clicca si Chiudi esce correttamente la finesta di richiesta salvatggio, ma non deve uscire il loading panel.

![image](https://cloud.githubusercontent.com/assets/4960206/4952637/075f8258-6677-11e4-9329-f796394a4818.png)

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
Ok
