### ISSUE TITLE
Errore cursore strano in caselle di testo

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#61]
Nelle caselle dei dati generali relativi al cognome e nome de cuius permane il problema del cursore:
![image](https://cloud.githubusercontent.com/assets/9605890/5613403/191a0c84-94e4-11e4-95e4-6954316ecbda.png)

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
Ok! Controllato funziona
