### ISSUE TITLE
Errore generazione elenco successori nell'albero genealogico

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#62]
3)  Errore lista dei successori nell’albero genealogico testuale e grafico: ho inserito tre successori e viene visualizzato solo il primo. il file di test è una nuova successione: Test_32_successione_Multidata.msu
![image](https://cloud.githubusercontent.com/assets/9605890/5613417/48e8fb0a-94e4-11e4-8f34-e712cca6150f.png)

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
Controllato. A posto!
