### ISSUE TITLE
Inserimento valore di quota dei beni

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#63]
Inserimento valore quota di proprietà di un immobile: intendevo inserire un valore pari a 1000/1000 ma vedi cosa dice: 
![image](https://cloud.githubusercontent.com/assets/9605890/5613429/6e420e6e-94e4-11e4-8563-a96c443dbb89.png)

Poi ho capito che si è obbligati a cambiare prima il valore nel denominatore per via del calcolo automatico del valore dell'immobile che il programma esegue a ogni digitazione.

**Comment by armandomusto** [comment]
Per adesso va bene così anche perchè non mi viene in mette nessuna soluzione visto che numeratore e denominatore sono due numeri separati, a meno di mettere un esplicito bottone Calcola a fianco del denominatore

**Comment by skate68** [comment]
E se mettiamo il bottone calcola a fianco della casella valore (come gia e)
e disabilitiamo il calcolo automatico a ogni digitazione? Perché mi sembra
questo che genera il problema
Il 07/gen/2015 21:23 "armandomusto" notifications@github.com ha scritto:

**Comment by armandomusto** [comment]
Certo che si può fare, ma se il bottone non viene cliccato il valore non si aggiorna...

**Comment by armandomusto** [comment]
Fatto

**Comment by skate68** [comment]
Adesso presenta un altro problema:
![image](https://cloud.githubusercontent.com/assets/9605890/5730289/231bba66-9b79-11e4-93b5-76804d273425.png)

**Comment by armandomusto** [comment]
Ripristinato il calcolo automatico, purtroppo è inevitabile visto che è collegato automaticamente al valore della quota. Il messaggio è stato disabilitato e il salvataggio risolto.

**Comment by skate68** [comment]
ok
