### ISSUE TITLE
Calcolo automatico età usufruttuario e nuda proprietà

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#64]
Nella dialogbox dei beni immobili (Quadro B:1) quando si sceglie il tipo di diritto “Usufrutto” o “Nuda proprietà” il bottone a fianco della casella che si apre (calcolatrice) dovrebbe aprire una piccola dialogbox in cui inserire la data di nascita di cui calcolare automaticamente l’età da far apparire nella casella
![image](https://cloud.githubusercontent.com/assets/9605890/5613464/01b464e4-94e5-11e4-83d1-3f4361740f68.png)

**Comment by armandomusto** [comment]
Ma l'età dell'usufruttuario rispetto a quale data deve essere calcolata? La data della successione o la data di inserimento?

**Comment by skate68** [comment]
Arma' alla data  di nascita dellusufruttuario che l'utente inserisce nella
casellina che si apre. Guarda come funziona blumatica e ti renderai conto
subito ;-)
Il 09/gen/2015 22:01 "armandomusto" notifications@github.com ha scritto:

**Comment by armandomusto** [comment]
Questo l'avevo capito pure io che bisogna inserire la data di nascita, ma serve sapere rispetto a quale altra data fare la differenza, in pratica che età bisogna considerare quando si è aperta la successione o ad oggi?

**Comment by skate68** [comment]
Rispetto a oggi perché da tale data dipende anche il valore della nuda
proprietà.  Anche se non hai detto una cazzata, per queste funzionalità
accessorie non conviene complicarci troppo la vita
Il 10/gen/2015 08:31 "armandomusto" notifications@github.com ha scritto:

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
Ok a posto!
