### ISSUE TITLE
Errori ripartizione valore dei beni agli eredi

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#65]
C’è ancora un piccolo problema nella ripartizione dei valori dei beni agli eredi:
![image](https://cloud.githubusercontent.com/assets/9605890/5613476/24bba4b6-94e5-11e4-910a-1928b46d5d57.png)
Un altro errore nella ripartizione dei valori. Ho chiuso e riaperto il file Test_32... e ho inserito, clonandolo, un altro erede (terza figlia). la procedura di assegnazione delle quote ha funzionato benissimo, ma nella ripartizione dei valori dei beni agli eredi guarda che succede:
![image](https://cloud.githubusercontent.com/assets/9605890/5613488/485b5254-94e5-11e4-8a43-8a8e4f084ebb.png)

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
Ok! Controllato funziona
