### ISSUE TITLE
Gestione griglia degli eredi

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#66]
la freccia che sta su dovrebbe avere il tool tip “Sposta su” e viceversa:
![image](https://cloud.githubusercontent.com/assets/9605890/5613502/755bfc68-94e5-11e4-9442-2737b1b22d30.png)

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
Ok! Controllato funziona
