### ISSUE TITLE
Gestione valori di quota trasferite

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#67]
Input bene quadri B2 e B3: le caselle per l’inserimento della quota trasferita sono fisse su due cifre quando dovrebbero essere almeno quattro:
![image](https://cloud.githubusercontent.com/assets/9605890/5613515/9b0ce6f2-94e5-11e4-8add-6af2b171132d.png)

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
Ok. A Posto!
