### ISSUE TITLE
Stampa Modello F23

### ISSUE THREAD

**Issue by armandomusto** [EmmeEsse/ESSE#68]
Implementare la stampa con i nuovi template

**Comment by armandomusto** [comment]
- [x] Sistemare i template
- [x] Testare di nuovo quando completato #69 
- [ ] Testare di nuovo quando completato #77

**Comment by skate68** [comment]
1)  Ulteriori miglioramenti: Aprire sempre la finestra di stampa (per tutti i moduli) al massimo delle dimensioni. Se possibile zoomare anche il modello stampato nella finestra di anteprima al massimo delle dimensioni:
![image](https://cloud.githubusercontent.com/assets/9605890/5778205/eb2f79a8-9d99-11e4-9a36-2e18ed4f40dd.png)
23) Stampa Modello F23 – campi non valorizzati:
![image](https://cloud.githubusercontent.com/assets/9605890/5778219/0495fe08-9d9a-11e4-9dcf-9df06ed330b3.png)

**Comment by armandomusto** [comment]
Risolto online. Mancano ancora i concessionari.

**Comment by armandomusto** [comment]
Aggiunto anche il concessionario

**Comment by skate68** [comment]
Ok
