### ISSUE TITLE
Sezione Tributi Speciali

### ISSUE THREAD

**Issue by armandomusto** [EmmeEsse/ESSE#69]
![image](https://cloud.githubusercontent.com/assets/4960206/5692969/34b6ee24-990a-11e4-819c-8e63e4c661ab.png)
- [x] Creare una tabella per salvare un elenco di tributi. Tale elenco deve esse manutenibile. Nelle opzioni di default dell'applicazione deve essere possibile salvare una selezione di tributi, questo elenco deve essere caricato all'interno del file quando si crea una nuova successione. Ogni successione può gestire in modo autonomo l'elenco dei tributi.
- [x] Impostare i tributi nella stampa del prospetto di autoliquidazione

**Comment by armandomusto** [comment]
In test

**Comment by skate68** [comment]
I tributi speciali non sono l'imposta ipotecaria, catastale e così via ... ma dei tributi aggiuntivi che si versano in maniera diversa nei vari uffici. Nella lista dei tributi speciali di Esse devono comparire pari pari i codici e i relativi tributi così come appaiono in quella di blumatica:
![image](https://cloud.githubusercontent.com/assets/9605890/6315040/d90967da-b9f4-11e4-9c27-6176ec554e14.png)

Solo il primo è il tributo speciale usato di solito, gli altri sono a discrezione degli utenti. Gli ultimi due sono addirittura completamente personalizzabili (codice, causale, ecc.). Ma anche quando saranno selezionati più tributi speciali questi verranno tutti stampati in un'unica riga sia nel mod. F23 che nel prospetto di autoliquidazione delle imposte

**Comment by armandomusto** [comment]
Risolto. Aggiornamento online.

**Comment by skate68** [comment]
fallo comparire così, con i tributi speciali di default impostati a 20,66 ma con tutti i check deselezionati:
![image](https://cloud.githubusercontent.com/assets/9605890/6382323/d2d8a08c-bd47-11e4-93ef-b7d4e1fd5e1b.png)

Poi nella stampa del prospetto di autoliquidazione riporti solo la dicitura: Tributi speciali (codice, codice, codice, ....)

Solo di quelli effettivamente valorizzati. Altrimenti, se nemmeno uno è stato selezionato non riportare nemmeno gli importi a zero:

![image](https://cloud.githubusercontent.com/assets/9605890/6382358/2dd0a2be-bd48-11e4-9ef1-2f17221a7c5f.png)

![image](https://cloud.githubusercontent.com/assets/9605890/6382369/509a1cda-bd48-11e4-8f1f-c7c06ed51e0b.png)

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
ok. A posto!
