### ISSUE TITLE
Opzioni - Dati del dichiarante

### ISSUE THREAD

**Issue by armandomusto** [EmmeEsse/ESSE#72]
Verificare il salvataggio dei dati del dichiarante nelle opzioni di default. Quando è stato salvato un dichiarante di default deve essere visibile nell'elenco dei dichiaranti della successione.

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
Questa parte non funziona ancora bene. Ho aperto la finestra quando mi ha notificato che non era stato selezionato il dichiarante (ma poi comunque va in stampa mentre dovrebbe presentare una opzione Stampare/Selezionare dichiarante). Poi c'è un funzionamento strano se clicchi sull'etichetta Strumenti che ricompare al suo interno: si apre a tutto schermo la finestra di dialogo e per tornare indietro bisogna uscire dalla successione:
![image](https://cloud.githubusercontent.com/assets/9605890/5730096/bf1b5fcc-9b77-11e4-950c-d88a1ec63dbd.png)

**Comment by skate68** [comment]
Anche in questa finestra c'è da sistemare ancora delle cose:
![image](https://cloud.githubusercontent.com/assets/9605890/5730131/02b0f1e8-9b78-11e4-96e1-527c40010015.png)

A proposito come si selezionano gli eredi presenti nella successione corrente?

**Comment by armandomusto** [comment]
Dovevi aprire la sezione Strumenti della Successione

**Comment by armandomusto** [comment]
Nella combo box di sopra ciuccio!!!

Il giorno 13 gennaio 2015 23:01, skate68 notifications@github.com ha
scritto:

> Anche in questa finestra c'è da sistemare ancora delle cose:
> [image: image]
> https://cloud.githubusercontent.com/assets/9605890/5730131/02b0f1e8-9b78-11e4-96e1-527c40010015.png
> 
> A proposito come si selezionano gli eredi presenti nella successione
> corrente?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EmmeEsse/ESSE/issues/72#issuecomment-69829202.

## 

Armando Musto

mobile : +39 3479537809

**Comment by skate68** [comment]
Sì ho visto! Grazie. Praticamente dipende da dove la apri

Il giorno 13 gennaio 2015 23:03, armandomusto notifications@github.com ha
scritto:

**Comment by armandomusto** [comment]
Ho nascosto il link STRUMENTI quando si apre la successione, non serve anche perchè dalla successione è sempre possibile cambiare le opzioni e farle diventare di default.

La combo con i dichiaranti è riempita solo quando l'opzioni sono aperte dalla successione.
Il layout va bene così, è ben bilanciato anche se qualche campo è più esteso del previsto. Ho sistemato su una sola riga Telefono e Tipo Dichiarante.
Per quanto riguarda il CAP, se l'indirizzo è obbligatorio anche il CAP deve esserlo.

**Comment by skate68** [comment]
E non puoi fare che almeno nei luoghi in cui è unico il programma lo scrive
in automatico?
Il 14/gen/2015 12:14 "armandomusto" notifications@github.com ha scritto:

**Comment by armandomusto** [comment]
C'è già un ticket per questa modifica #41

**Comment by skate68** [comment]
Ok! A posto
