### ISSUE TITLE
Asse Ereditario - Importazione visura pdf

### ISSUE THREAD

**Issue by armandomusto** [EmmeEsse/ESSE#73]
Deve essere possibile importare i dati di un bene mediante caricamento di una visura catastale (documento pdf)

**Comment by armandomusto** [comment]
Aggiunta

**Comment by skate68** [comment]
Mi da errore quando cerco di aprire un file pdf:
![image](https://cloud.githubusercontent.com/assets/9605890/9561029/15ed8c10-4e35-11e5-81b1-b287b8defab9.png)

**Comment by armandomusto** [comment]
Nella cartella di installazione devi avere la cartella pdfConvert copiala da Dropbox

**Comment by skate68** [comment]
Ok
Il 01/Set/2015 07:07, "armandomusto" notifications@github.com ha scritto:
