### ISSUE TITLE
Albero Grafico - Layout box 

### ISSUE THREAD

**Issue by armandomusto** [EmmeEsse/ESSE#75]
![image](https://cloud.githubusercontent.com/assets/4960206/5711875/195ef7b6-9aae-11e4-9f8b-ca06555bbda3.png)

**Comment by skate68** [comment]
Adesso funziona ma bisogna inserire gli altri dati nel box

**Comment by armandomusto** [comment]
Bravo, saresti così gentile da dire quali sono...

**Comment by skate68** [comment]
Ecquante volte ti devo mandare il disegno?
Il 16/gen/2015 19:18 "armandomusto" notifications@github.com ha scritto:

**Comment by armandomusto** [comment]
Ma quale cazzo e disegno?

**Comment by skate68** [comment]
![image](https://cloud.githubusercontent.com/assets/9605890/6382211/17baa944-bd47-11e4-9617-22a9ee5b302b.png)

**Comment by skate68** [comment]
Obbligatorie: Cognome  (ragione sociale), Nome, luogo nascita (sede legale), data nascita, e grado e rapporto di parentela (qui devi preferire l'eventuale dicitura relativa al rapporto di parentela inserita dall'utente)

Opzionali: codice fiscale.

**Comment by armandomusto** [comment]
Per adesso ho messo anche il CF, alla fine una sola informazione non fa tanta differenza

**Comment by skate68** [comment]
Infatti
Il 24/Mar/2015 18:46 "armandomusto" notifications@github.com ha scritto:

**Comment by skate68** [comment]
Adesso va bene OK!
