### ISSUE TITLE
Errore installazione nuova versione

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#76]
Armando, c'è qualche problema con la nuova cartella di installazione. Non so se si risolve, così come mi hai anticipato, con la copia dei file nella cartella DEvExpress perché credo che non dipenda da quello. Ti allego le diagnostiche così capisci e mi spieghi come fare x continuare le operazioni di testing:
La prima diagnostica al momento della generazione del CF:
![image](https://cloud.githubusercontent.com/assets/9605890/5718758/69f43a52-9b11-11e4-9652-09fbf352e876.png)

Poi in fase di stampa del Modello 4:
![image](https://cloud.githubusercontent.com/assets/9605890/5718771/819e86bc-9b11-11e4-9d1e-a6f0436e6a37.png)

E infine....
![image](https://cloud.githubusercontent.com/assets/9605890/5718775/8b485dc8-9b11-11e4-9ece-dd6a77c161b9.png)

**Comment by armandomusto** [comment]
Verifica se il file CodiceFiscale.lib è presente nella cartella, altrimenti prendila da quella vecchia. Questo file non ha nessuna dipendenza con le DevExpress.
Per quanto riguarda la stampa del modello potrebbe essere legato alle DevExpress, ma mi devi dire anche su quale file ha generato il problema

**Comment by skate68** [comment]
Il file con cui ho provato è il: Test33.... che ti aggiungo in dropbox.
Ho risolto il problema del CF ma permane quello della stampa.
Ciao

Il giorno 13 gennaio 2015 10:53, armandomusto notifications@github.com ha
scritto:

**Comment by armandomusto** [comment]
Mandami il file per poste, non posso accedere a dropbox

Il giorno 13 gennaio 2015 12:22, skate68 notifications@github.com ha
scritto:

> Il file con cui ho provato è il: Test33.... che ti aggiungo in dropbox.
> Ho risolto il problema del CF ma permane quello della stampa.
> Ciao
> 
> Il giorno 13 gennaio 2015 10:53, armandomusto notifications@github.com
> ha
> scritto:
> 
> > Verifica se il file CodiceFiscale.lib è presente nella cartella,
> > altrimenti prendila da quella vecchia. Questo file non ha nessuna
> > dipendenza con le DevExpress.
> > Per quanto riguarda la stampa del modello potrebbe essere legato alle
> > DevExpress, ma mi devi dire anche su quale file ha generato il problema
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/EmmeEsse/ESSE/issues/76#issuecomment-69720074.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EmmeEsse/ESSE/issues/76#issuecomment-69730416.

## 

Armando Musto

mobile : +39 3479537809

**Comment by skate68** [comment]
Ok! Risolto
