### ISSUE TITLE
Errori Input dati immobili

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#78]
la casella sotto non consente di inserire, e di conseguenza stampare, numeri decimali:
![image](https://cloud.githubusercontent.com/assets/9605890/5730433/5fa42f1c-9b7a-11e4-8c43-b55db455fd9f.png)

**Comment by skate68** [comment]
Un altro problema rilevato:
![image](https://cloud.githubusercontent.com/assets/9605890/5730486/cab5d206-9b7a-11e4-944f-325a63750370.png)

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
Controllato a posto!
