### ISSUE TITLE
Stampa Modello 4 – Indicazione dei quadri utilizzati:

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#79]
Sistemare questa cosa:
![image](https://cloud.githubusercontent.com/assets/9605890/5730500/fab42f0c-9b7a-11e4-8124-2dcb49ee5812.png)

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
C'è ancora qualcosa che non va:
in una successione ho inserito un solo bene del Quadro B:2 (azioni) e nessuna azienda Quadro B:3:
![image](https://cloud.githubusercontent.com/assets/9605890/5778093/ef101b0a-9d98-11e4-8435-9493588fe101.png)
![image](https://cloud.githubusercontent.com/assets/9605890/5778096/f93aa320-9d98-11e4-83a4-58c17c269c7f.png)

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
ok verificato
