### ISSUE TITLE
Stampa Modello 4  (a)

### ISSUE THREAD

**Issue by armandomusto** [EmmeEsse/ESSE#8]
- [x] A. Il simbolo dell’euro e l’eventuale scrittura dei valori pari a zero, nel frontespizio della dichiarazione e nelle altre caselle ove ricorrono, deve essere opzionabile da parte dell’utente.
  ![image](https://cloud.githubusercontent.com/assets/4960206/4952812/17435832-6679-11e4-9341-b39081c2e987.png)
- [x] B. ![image](https://cloud.githubusercontent.com/assets/4960206/4952821/284d6046-6679-11e4-87a3-4dd42746c61a.png)
  Controllare la numerazione progressiva:
- [x] C. ![image](https://cloud.githubusercontent.com/assets/4960206/4952833/41a45aa4-6679-11e4-9f1c-e3e1c2f20efe.png)
- [ ] D. ![image](https://cloud.githubusercontent.com/assets/4960206/4952837/4b30087a-6679-11e4-9764-629e7e4a4037.png)

**Comment by skate68** [comment]
- [x] E. prova con i nuovi moduli a stampare il modello 4 e ti accorgerai che alcuni quadri vengono moltiplicati. Mappa tutti i campi in modo da avere una stampa completa.
  C'è anche da sistemare le righe per i modelli: B5 e quadro C:
  ![image](https://cloud.githubusercontent.com/assets/9605890/5541067/764bf540-8ad3-11e4-9024-521d4da57331.png)
  ![image](https://cloud.githubusercontent.com/assets/9605890/5541072/8163f680-8ad3-11e4-8005-fd170257d7bf.png)

**Comment by armandomusto** [comment]
Punti B,C,E risolti. Aggiornamento su DropBox

**Comment by armandomusto** [comment]
Anche il punto A è risolto
