### ISSUE TITLE
Errori generazione e stampa prospetti di calcolo

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#84]
Bisogna sistemare urgentemente queste cose per proseguire nella fase dei test anche per il calcolo dell'invim
![image](https://cloud.githubusercontent.com/assets/9605890/6315053/a73306d4-b9f5-11e4-9b48-0c56c18fabd6.png)

![image](https://cloud.githubusercontent.com/assets/9605890/6315054/b0e88186-b9f5-11e4-8f81-5602b8875608.png)

**Comment by skate68** [comment]
![image](https://cloud.githubusercontent.com/assets/9605890/6315059/e9e831e8-b9f5-11e4-9a51-78c19cc7a28c.png)

![image](https://cloud.githubusercontent.com/assets/9605890/6315060/f077c5d2-b9f5-11e4-8194-f4a8a6517296.png)

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
L'errore si ripete ancora

**Comment by skate68** [comment]
Controlla anche questi altri errori di visualizzazione nei report di calcolo a video dell'invim:
![image](https://cloud.githubusercontent.com/assets/9605890/6382616/527d6424-bd4a-11e4-917b-3eab4928f93b.png)

**Comment by armandomusto** [comment]
Risolto il problema della sovrapposizione e del calcolo Invim Detraibile. Per quanto riguarda l'errore di stampa ho testato tutte le stampe. Se l'errore persiste mandami il file e il log.

**Comment by skate68** [comment]
ok a posto!
