### ISSUE TITLE
Finestra gestione Tributi speciali

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#87]
Sarebbe meglio fare così:
![image](https://cloud.githubusercontent.com/assets/9605890/6382632/7d877272-bd4a-11e4-919f-a71475c26138.png)

**Comment by armandomusto** [comment]
Risolto

**Comment by skate68** [comment]
Si potrebbero fare questi piccoli aggiustamenti? C'è ancora qualcosa che non va
![image](https://cloud.githubusercontent.com/assets/9605890/6440487/b2e9a76e-c0dd-11e4-8c04-388d802b88f2.png)

![image](https://cloud.githubusercontent.com/assets/9605890/6440492/bb7be69e-c0dd-11e4-883d-f191ed137765.png)

**Comment by armandomusto** [comment]
Ma le imposte che stai descrivendo tu mica sono Tributi Speciali?

**Comment by skate68** [comment]
Per errore l'altra volta ho inserito in questa Issue un'immagine che si
riferiva a un'altra cosa. Comunque queste due finestre che ho inserito
adesso incidono sulla stampa del prospetto di liquidazione e dell'F23. La
prima è specifica proprio per i tributi speciali.

2015-03-02 13:14 GMT+01:00 armandomusto notifications@github.com:

**Comment by armandomusto** [comment]
Comunque questo elenco è solo per i tributi speciali

**Comment by skate68** [comment]
Sì. ma che ci metti anche la correzione della parte relativa a formalità e conservatorie non è un grande problema ...?

**Comment by armandomusto** [comment]
Formalità e conserv si può correggere
Il 02/Mar/2015 13:24 "skate68" notifications@github.com ha scritto:

**Comment by armandomusto** [comment]
Problema formalità corretto

**Comment by skate68** [comment]
ok

**Comment by armandomusto** [comment]
```
a { color: #007ee6; text-decoration:underline; }           Keeper protects us from being hacked.  It securely stores my passwords and private info.   Get Keeper Now   You can also click here to accept your invitation to Keeper.                   Never forget a password again Keeper creates high-strength passwords for you and saves them in your own private vault so you can access them anytime.    Save your passwords, private files and photos everywhere Keeper securely and instantly syncs to all of your devices and computers.    Auto-fill your passwords on websites for fast, secure access. Keeper is fast and saves you time by filling in your passwords on all your websites and mobile apps.    Share records with people you trust, whenever you need to. Keeper lets you quickly and securely share with others from vault-to-vault.  You can also click here to accept your invitation to Keeper.  Keeper will not subscribe you to marketing emails because you received this invitation. If you'd like to help a friend get protected with Keeper, please forward this email to them.
```
