### ISSUE TITLE
Stampa modello F23

### ISSUE THREAD

**Issue by skate68** [EmmeEsse/ESSE#90]
Ci sono delle piccole cose da sistemare anche in questa sezione:

![image](https://cloud.githubusercontent.com/assets/9605890/6382734/79a96100-bd4b-11e4-8aeb-ae30ac424edc.png)

![image](https://cloud.githubusercontent.com/assets/9605890/6382744/87749cd2-bd4b-11e4-93e4-5526e833ff5c.png)

**Comment by armandomusto** [comment]
Perchè i decimali dovrebbero essere tutti zero? Devono essere sempre a zero nonostante il loro valore effettivo?
P.S: Ricordati sempre di menzionare il file usato per il test.

**Comment by skate68** [comment]
No no devono essere quello che realmente sono non le prime due cifre della
parte intera
Il 27/Feb/2015 09:36 "armandomusto" notifications@github.com ha scritto:

**Comment by armandomusto** [comment]
Risolto, drop box aggiornato

**Comment by skate68** [comment]
Ecco cosa mi dice quando lancio la stampa del modello F23:
![image](https://cloud.githubusercontent.com/assets/9605890/6438973/6fbe273a-c0ce-11e4-9ccd-e41df1a6817c.png)

**Comment by armandomusto** [comment]
Carica pure il file

**Comment by skate68** [comment]
I file li ho caricati già  la settimana scorsa. Sono quelli numero 36. Mo
ti mando il log
Il 02/Mar/2015 11:23 "armandomusto" notifications@github.com ha scritto:

**Comment by armandomusto** [comment]
BUg risolto. Dropbox aggiornato

**Comment by skate68** [comment]
Ok
